### ISSUE TITLE
Assertion fail on `./test_run.py -m janus`

### ISSUE THREAD

**Issue by jmhelt** [NYU-NEWS/janus#14]
I am trying to set up a local instance of Janus on Ubuntu 18.04 and, following the README directions, built and installed Janus with no issues. However, running the first test command, `./test_run.py -m janus`, shows that all tests fail. The stack trace points to a failed assertion at line 20 of reactor.cc:
```c++
std::shared_ptr<Coroutine> Coroutine::CurrentCoroutine() {
  verify(sp_running_coro_th_);
  return sp_running_coro_th_;
}
```
because the current coroutine pointer is not initialized. The stack trace when running `build/deptran_server -f config/janus.yml -f config/1c1s1p.yml -f config/rw.yml -P localhost -d 20` (first test run by test_run.py) is:
```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff61b2801 in __GI_abort () at abort.c:79
#2  0x000055555577c124 in rrr::Coroutine::CurrentCoroutine () at ../src/rrr/reactor/reactor.cc:20
#3  0x000055555577af42 in rrr::Event::Event (this=0x55555630e408, coro=std::shared_ptr<rrr::Coroutine> (empty) = {...}) at ../src/rrr/reactor/event.cc:55
#4  0x0000555555601171 in rrr::IntEvent::IntEvent (this=0x55555630e408) at ../src/rrr/reactor/event.h:33
#5  0x0000555555601442 in janus::Tx::Tx (this=0x55555630e400, epoch=0, tid=281474976710657, mgr=0x0) at ../src/deptran/2pl/../classic/../tx.h:85
#6  0x00005555556d4065 in janus::TxRococo::TxRococo (this=0x55555630e400, id=281474976710657) at ../src/deptran/rococo/tx.cc:20
#7  0x0000555555686ee0 in janus::Graph<janus::TxRococo>::CreateV (this=0x7fffe2fa3750, id=281474976710657) at ../src/deptran/rococo/graph.h:122
#8  0x000055555568df79 in janus::JanusCommo::<lambda(rrr::Future*)>::operator()(rrr::Future *) const (__closure=0x555567e71b60, fu=0x555567ea60d0) at ../src/deptran/janus/commo.cc:25
#9  0x000055555568fcf4 in std::_Function_handler<void(rrr::Future*), janus::JanusCommo::SendDispatch(std::vector<janus::SimpleCommand>&, const std::function<void(int, std::map<unsigned int, std::map<int, mdb::Value> >&, janus::RccGraph&)>&)::<lambda(rrr::Future*)> >::_M_invoke(const std::_Any_data &, rrr::Future *&&) (__functor=..., __args#0=@0x7fffe2fa3800: 0x555567ea60d0) at /usr/include/c++/7/bits/std_function.h:316
#10 0x000055555578a97b in std::function<void (rrr::Future*)>::operator()(rrr::Future*) const (this=0x555567ea60f0, __args#0=0x555567ea60d0) at /usr/include/c++/7/bits/std_function.h:706
#11 0x0000555555788c64 in rrr::Future::notify_ready (this=0x555567ea60d0) at ../src/rrr/rpc/client.cpp:69
#12 0x0000555555789770 in rrr::Client::handle_read (this=0x55555633e000) at ../src/rrr/rpc/client.cpp:213
#13 0x000055555577dc3a in rrr::Epoll::Wait (this=0x555567e726c0) at ../src/rrr/reactor/epoll_wrapper.h:209
#14 0x000055555577cbe3 in rrr::PollMgr::PollThread::poll_loop (this=0x555567e726c0) at ../src/rrr/reactor/reactor.cc:188
#15 0x000055555577e113 in rrr::PollMgr::PollThread::start_poll_loop (arg=0x555567e726c0) at ../src/rrr/reactor/reactor.cc:117
#16 0x00007ffff70b16db in start_thread (arg=0x7fffe2fa4700) at pthread_create.c:463
#17 0x00007ffff629388f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

And the log output (with debug logging enabled is:
```
I [s_main.cc:117] 2019-05-28 14:32:16.821 | PWD : 
I [s_main.cc:129] 2019-05-28 14:32:16.821 | starting process 7959
I [config.cc:268] 2019-05-28 14:32:16.821 | LoadYML: config/janus.yml
I [config.cc:268] 2019-05-28 14:32:16.821 | LoadYML: config/1c1s1p.yml
I [config.cc:383] 2019-05-28 14:32:16.821 | BuildSiteProcMap
I [config.cc:268] 2019-05-28 14:32:16.821 | LoadYML: config/rw.yml
I [config.cc:632] 2019-05-28 14:32:16.822 | group size: 1
I [s_main.cc:25] 2019-05-28 14:32:16.822 | client_setup_heartbeat
I [s_main.cc:66] 2019-05-28 14:32:16.822 | server enabled, number of sites: 1
I [s_main.cc:91] 2019-05-28 14:32:16.822 | waiting for client setup threads.
I [s_main.cc:74] 2019-05-28 14:32:16.822 | launching site: 0, bind address 0.0.0.0:8101
I [server_worker.cc:76] 2019-05-28 14:32:16.822 | start data population for site 0
I [server_worker.cc:104] 2019-05-28 14:32:19.407 | data populated for site: 0, partition: 0
I [s_main.cc:82] 2019-05-28 14:32:19.407 | table popped for site 0
I [server_worker.cc:120] 2019-05-28 14:32:19.407 | enter SetupService for s101 @ 0.0.0.0:8101
D [server_worker.cc:163] 2019-05-28 14:32:19.407 | starting server at 0.0.0.0:8101
I [server.cpp:441] 2019-05-28 14:32:19.407 | rrr::Server: started on 0.0.0.0:8101
I [server_worker.cc:171] 2019-05-28 14:32:19.407 | Server s101 ready at 0.0.0.0:8101
I [s_main.cc:85] 2019-05-28 14:32:19.407 | start communication for site 0
I [communicator.cc:161] 2019-05-28 14:32:19.408 | connect to site: 127.0.0.1:8101 (attempt 0)
D [client.cpp:150] 2019-05-28 14:32:19.408 | rrr::Client: connected to 127.0.0.1:8101
D [server.cpp:372] 2019-05-28 14:32:19.408 | rrr::Server: got new client, fd=7
D [communicator.cc:167] 2019-05-28 14:32:19.408 | connect to site: 127.0.0.1:8101 success!
I [s_main.cc:87] 2019-05-28 14:32:19.408 | site 0 launched!
I [s_main.cc:95] 2019-05-28 14:32:19.408 | done waiting for client setup threads.
I [s_main.cc:102] 2019-05-28 14:32:19.408 | server workers' communicators setup
I [s_main.cc:49] 2019-05-28 14:32:19.408 | client enabled, number of sites: 1
I [communicator.cc:161] 2019-05-28 14:32:19.413 | connect to site: 127.0.0.1:8101 (attempt 0)
D [client.cpp:150] 2019-05-28 14:32:19.413 | rrr::Client: connected to 127.0.0.1:8101
D [server.cpp:372] 2019-05-28 14:32:19.413 | rrr::Server: got new client, fd=10
D [communicator.cc:167] 2019-05-28 14:32:19.413 | connect to site: 127.0.0.1:8101 success!
D [client_worker.cc:293] 2019-05-28 14:32:19.413 | client 1 created; forward 0
D [client_worker.cc:135] 2019-05-28 14:32:19.414 | Work: 1
I [s_main.cc:121] 2019-05-28 14:32:19.414 | wait_for_clients: wait for client threads to exit.
I [communicator.cc:69] 2019-05-28 14:32:19.414 | Done waiting to connect to client leaders.
D [client_worker.cc:146] 2019-05-28 14:32:19.414 | after wait for start
I [client_worker.cc:152] 2019-05-28 14:32:19.414 | closed loop clients.
I [client_worker.cc:129] 2019-05-28 14:32:19.414 | coordinator 65536 created at site 1: forward 0
D [client_worker.cc:156] 2019-05-28 14:32:19.414 | create coordinator 65536
D [client_worker.cc:198] 2019-05-28 14:32:19.414 | wait for finish... 1
D [reactor.cc:36] 2019-05-28 14:32:19.414 | create a coroutine scheduler
I [client_worker.cc:249] 2019-05-28 14:32:19.414 | DispatchRequest: 1
D [coordinator.cc:66] 2019-05-28 14:32:19.414 | assigning tx id: 1000000000001
D [coordinator.cc:72] 2019-05-28 14:32:19.414 | do one request txn_id: 1
I [coordinator.cc:85] 2019-05-28 14:32:19.414 | start txn!!! : 0
D [procedure.cc:159] 2019-05-28 14:32:19.414 | getting piece data piece id: 101
D [commo.cc:39] 2019-05-28 14:32:19.414 | dispatch to 0
D [reactor.cc:36] 2019-05-28 14:32:19.415 | create a coroutine scheduler
D [scheduler.cc:44] 2019-05-28 14:32:19.415 | create tid 1000000000001
  *** verify failed: sp_running_coro_th_ at ../src/rrr/reactor/reactor.cc, line 20
  *** begin stack trace ***
0    /home/jhelt/git/janus/build/deptran_server(+0x20c116) [0x555555760116]
1    /home/jhelt/git/janus/build/deptran_server(+0x22811f) [0x55555577c11f]
2    /home/jhelt/git/janus/build/deptran_server(+0x226f42) [0x55555577af42]
3    /home/jhelt/git/janus/build/deptran_server(+0xad171) [0x555555601171]
4    /home/jhelt/git/janus/build/deptran_server(+0xad442) [0x555555601442]
5    /home/jhelt/git/janus/build/deptran_server(+0x180065) [0x5555556d4065]
6    /home/jhelt/git/janus/build/deptran_server(+0x132ee0) [0x555555686ee0]
7    /home/jhelt/git/janus/build/deptran_server(+0x139f79) [0x55555568df79]
8    /home/jhelt/git/janus/build/deptran_server(+0x13bcf4) [0x55555568fcf4]
9    /home/jhelt/git/janus/build/deptran_server(+0x23697b) [0x55555578a97b]
10   /home/jhelt/git/janus/build/deptran_server(+0x234c64) [0x555555788c64]
11   /home/jhelt/git/janus/build/deptran_server(+0x235770) [0x555555789770]
12   /home/jhelt/git/janus/build/deptran_server(+0x229c3a) [0x55555577dc3a]
13   /home/jhelt/git/janus/build/deptran_server(+0x228be3) [0x55555577cbe3]
14   /home/jhelt/git/janus/build/deptran_server(+0x22a113) [0x55555577e113]
15   /lib/x86_64-linux-gnu/libpthread.so.0(+0x76db) [0x7ffff70b16db]
```

Any ideas on how to fix this issue or further debug? This code doesn't seem to have changed in a while, so I'm not sure if it just hasn't been run since then, or if it is a platform-specific issue. Thanks in advance for your help! Let me know if you need any more info.

**Comment by shuaimu** [comment]
Thanks for reporting the issue. I've checked in a commit that should've fixed the issue. You are right that this repo is not under active development, only me playing with some c++ tricks every once in a while. And the aforementioned bug is caused by my previous commits trying to replace the asynchronous code with coroutines.

**Comment by jmhelt** [comment]
Great, thank you! I just checked the fix locally and confirmed it fixes the issue.
